export const homeListings = [
  {
    id: 1,
    title: "Spacious Apartment in Downtown",
    owner: " owner",
    area: "Downtown",
    price: 5000, 
    beds: 2,
    baths: 2,
    bhk:1,
    homeType: "Dependent",
    forRent: true, 
    imageUrl: "https://res.cloudinary.com/dr4fik8kg/image/upload/v1724499537/cld-sample-3.jpg",
    phoneNo: "123-456-7890",
    bargain: 'Negotiable',
    imageUrls: [
      "https://res.cloudinary.com/dr4fik8kg/image/upload/v1724499537/cld-sample-3.jpg",
      "https://res.cloudinary.com/dr4fik8kg/image/upload/v1724499527/samples/people/kitchen-bar.jpg",
      "https://res.cloudinary.com/dr4fik8kg/image/upload/v1724499528/samples/ecommerce/shoes.png"
    ],
    videoUrl: "https://example.com/video.mp4",
    amenities: ["Parking", "Gym", "Swimming Pool"],
    nearbyAreas: ["Park", "Supermarket", "School"],
  },
  {
    id: 2,
    title: "Modern Family Home",
    owner: "John Doe",
    area: "Downtown",
    price: 1200, 
    beds: 3,
    baths: 2,
    bhk:2,
    homeType: "Independent",
    forRent: true,
    imageUrl: "https://example.com/images/home1-1.jpg",
    phoneNo: "123-456-7890",
    bargain: true,
    amenities: ["Garage", "Pool", "Central Heating"],
    nearbyAreas: ["Shopping Mall", "Hospital"],
    imageUrls: [
      "https://example.com/images/home1-1.jpg",
      "https://example.com/images/home1-2.jpg"
    ],
    videoUrl: "https://example.com/videos/home1.mp4"
  },
  {
    id: 3,
    title: "Cozy Apartment",
    owner: "Jane Smith",
    area: "Downtown",
    price: 800, 
    beds: 1,
    baths: 1,
    bhk:3,
    homeType: "Dependent",
    forRent: false,
    imageUrl: "https://example.com/images/home2-1.jpg",
    phoneNo: "234-567-8901",
    bargain: false,
    amenities: ["Gym", "Elevator"],
    nearbyAreas: ["School", "Park"],
    imageUrls: [
      "https://example.com/images/home2-1.jpg",
      "https://example.com/images/home2-2.jpg"
    ]
  },
  {
    id: 4,
    title: "Luxury Villa",
    owner: "Michael Johnson",
    area: "Uptown",
    price: 3000, 
    beds: 4,
    bhk:2,
    baths: 3,
    homeType: "Independent",
    forRent: true,
    imageUrl: "https://example.com/images/home3-1.jpg",
    phoneNo: "345-678-9012",
    bargain: true,
    amenities: ["Private Garden", "Swimming Pool"],
    nearbyAreas: ["Beach", "Golf Course"],
    imageUrls: [
      "https://example.com/images/home3-1.jpg",
      "https://example.com/images/home3-2.jpg"
    ],
    videoUrl: "https://example.com/videos/home3.mp4"
  },
  {
    id: 5,
    title: "Cozy Studio for Rent",
    owner: "Jane Smith",
    area: "City Center",
    price: 1000, 
    beds: 1,
    bhk:2,
    baths: 1,
    homeType: "Dependent",
    forRent: false,
    imageUrl: "https://res.cloudinary.com/dr4fik8kg/image/upload/v1724499537/cld-sample-2.jpg",
    phoneNo: "098-765-4321",
    bargain: '',
    imageUrls: [
      "https://res.cloudinary.com/dr4fik8kg/image/upload/v1724499537/cld-sample-2.jpg",
      "https://res.cloudinary.com/dr4fik8kg/image/upload/v1724499537/cld-sample-4.jpg"
    ],
    videoUrl: "",
    amenities: ["Balcony", "Security", "Wi-Fi"],
    nearbyAreas: ["Mall", "Hospital", "Bus Stop"],
  },
  {
    id: 6,
    title: "Luxurious Villa with Pool",
    owner: "William Brown",
    area: "Uptown",
    price: 3000, 
    beds: 3,
    baths: 3,
    bhk:1,
    homeType: "Independent",
    forRent: true,
    imageUrl: "https://via.placeholder.com/150",
    phoneNo: "987-654-3210",
    bargain: 'Negotiable',
    imageUrls: [
      "https://res.cloudinary.com/dr4fik8kg/image/upload/v1724499528/samples/animals/three-dogs.jpg",
      "https://res.cloudinary.com/dr4fik8kg/image/upload/v1724499528/samples/people/bicycle.jpg"
    ],
    videoUrl: "",
    amenities: ["Private Garden", "Garage", "Terrace"],
    nearbyAreas: ["Beach", "Golf Course", "Market"],
  },
  {
    id: 7,
    title: "Modern Apartment with Great View",
    owner: "Emily Davis",
    area: "Midtown",
    price: 2000, 
    beds: 2,
    baths: 1,
    bhk:3,
    homeType: "Independent",
    forRent: false, 
    imageUrl: "https://via.placeholder.com/150",
    phoneNo: "456-789-0123",
    bargain: 'Negotiable',
    imageUrls: [
      "https://res.cloudinary.com/dr4fik8kg/image/upload/v1724499528/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dr4fik8kg/image/upload/v1724499528/samples/sheep.jpg"
    ],
    videoUrl: "https://example.com/video2.mp4",
    amenities: ["Laundry Room", "CCTV", "Elevator"],
    nearbyAreas: ["Gym", "Pharmacy", "Park"],
  }
];
